[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arcium_poker = "AshR4SHHiPJAKFbPjeeCkH4TNw82bbrJwmzbP4dThQKQ"

[programs.devnet]
arcium_poker = "AshR4SHHiPJAKFbPjeeCkH4TNw82bbrJwmzbP4dThQKQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
